# -*- coding: utf-8 -*-
"""由分类结果生成 sidebars.js"""
import json
from pathlib import Path

ROOT = Path(r"C:\Users\Jarlin\Desktop\Github\wikiDoc")
DOCS = ROOT / "docs"
data = json.loads(Path(ROOT / ".workbuddy/sidebar_groups.json").read_text(encoding="utf-8"))
trader, agent = data["trader"], data["agent"]

TRAder_ORDER = ["账户类型与选择", "账户管理与安全", "入金与出金", "交易品种与合约",
                "交易平台与工具", "交易操作与订单", "交易时间与市场规则", "错误与故障排除", "其他"]
AGENT_ORDER = ["计划与入门", "佣金与返佣", "个人专区与报告", "资金与平台安全", "其他"]


def js_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def sub_categories(groups, order, indent):
    pad = " " * indent
    out = []
    for label in order:
        items = groups.get(label, [])
        if not items:
            continue
        out.append(f"{pad}{{")
        out.append(f'{pad}  type: "category",')
        out.append(f"{pad}  label: {js_str(label)},")
        out.append(f"{pad}  collapsible: true,")
        out.append(f"{pad}  collapsed: true,")
        out.append(f"{pad}  items: [")
        for it in items:
            out.append(f"{pad}    {js_str(it)},")
        out.append(f"{pad}  ],")
        out.append(f"{pad}}},")
    return out


nytimes_items = []
for f in sorted((DOCS / "nytimes").glob("*.mdx")):
    if f.stem == "nytimes":
        continue
    nytimes_items.append(f"nytimes/{f.stem}")

lines = []
lines.append("/**")
lines.append(" * 侧栏按主题分类。此文件由 .workbuddy/gen_sidebars_js.py 生成。")
lines.append(" * 原先是单一 autogenerated 树，359 篇客户帮助平铺在同一个列表里，")
lines.append(" * 分类后便于按主题浏览。新增文档请手动加入对应分类。")
lines.append(" * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}")
lines.append(" */")
lines.append("const sidebars = {")
lines.append("  tutorialSidebar: [")
lines.append('    "index",')
# 客户帮助
lines.append("    {")
lines.append('      type: "category",')
lines.append('      label: "EXNESS 客户帮助",')
lines.append('      link: { type: "doc", id: "exness-trader/exness-trader" },')
lines.append("      collapsible: true,")
lines.append("      collapsed: true,")
lines.append("      items: [")
lines.extend(sub_categories(trader, TRAder_ORDER, 8))
lines.append("      ],")
lines.append("    },")
# 代理帮助
lines.append("    {")
lines.append('      type: "category",')
lines.append('      label: "EXNESS 代理帮助",')
lines.append('      link: { type: "doc", id: "exness-agent/exness-agent" },')
lines.append("      collapsible: true,")
lines.append("      collapsed: true,")
lines.append("      items: [")
lines.extend(sub_categories(agent, AGENT_ORDER, 8))
lines.append("      ],")
lines.append("    },")
# AI 与工具
lines.append("    {")
lines.append('      type: "category",')
lines.append('      label: "AI 与工具",')
lines.append("      collapsible: true,")
lines.append("      collapsed: true,")
lines.append("      items: [")
lines.append('        "chatgpt-edgegpt",')
lines.append('        "ea-setup",')
lines.append("      ],")
lines.append("    },")
# 纽时播报
lines.append("    {")
lines.append('      type: "category",')
lines.append('      label: "纽时播报",')
lines.append('      link: { type: "doc", id: "nytimes/nytimes" },')
lines.append("      collapsible: true,")
lines.append("      collapsed: true,")
lines.append("      items: [")
for it in nytimes_items:
    lines.append(f"        {js_str(it)},")
lines.append("      ],")
lines.append("    },")
lines.append("  ],")
lines.append("};")
lines.append("")
lines.append("module.exports = sidebars;")
lines.append("")

out = ROOT / "sidebars.js"
out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"已生成 {out}")
print(f"客户帮助分类: {[k for k in TRAder_ORDER if trader.get(k)]}")
print(f"代理帮助分类: {[k for k in AGENT_ORDER if agent.get(k)]}")
print(f"纽时播报: {len(nytimes_items)} 篇")
