/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: "autogenerated", dirName: "." },
    // External link
    {
      type: 'link',
      label: '嘉盛集团', // The link label
      href: 'https://s.ifttt.fun/jsmt4', // The external URL
    },
  ],
};

module.exports = sidebars;
