/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: "autogenerated", dirName: "." },
    // External link
    {
      type: 'link',
      label: '嘉盛集团', // The link label
      href: 'https://s.ifttt.fun/jsmt4', // The external URL
    },
    //   {
    //   type: 'html',
    //   value: '<a target="_blank" href="https://www.ifttt.fun/go/atfx-cn/"><img class="size-full wp-image-24489 aligncenter" src="https://cdn.fendou.la/bluehost/ATFX-ads.svg" alt="ATFX侧边栏广告" /></a>', // The HTML to be rendered
    //   defaultStyle: true, // Use the default menu item styling
    // },
    // {
    //   type: 'html',
    //   value: '<a  target="_blank" href="https://www.ifttt.fun/go/easymarket/"><img class="size-full wp-image-24489 aligncenter" src="https://cdn.fendou.la/welaowei8/2020/11/easyMarketsAds.svg" alt="easymarkets易信侧边栏广告" /></a>', // The HTML to be rendered
    //   defaultStyle: true, // Use the default menu item styling
    // },
  ],
};

module.exports = sidebars;
