name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: yarn

      - name: Install dependencies
        run: yarn install --check-files
      - name: install local search[CHINESE]
        run: yarn add @easyops-cn/docusaurus-search-local
      - name: Build website
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: '.github,node_modules'
          publish_dir: ./build

# 使用`deploy_key`的时候 将私钥设置为包含此操作的版本库，将公钥设置为外部版本库。
# 密钥生成在`C:\Users\hank\.ssh`注意查找 添加私钥到仓库/settings/secrets/actions.
# 只能使用 `personal_token`登录后，点击右上角的个人头像，然后在下拉菜单中选择 "Settings"（设置）。
# 访问 Developer settings：在设置页面的左侧菜单中，找到 "Developer settings"（开发者设置）并点击。
      - name: Deploy to wiki.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          #deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          exclude_assets: '.github,node_modules'
          external_repository: jarlin8/wiki.github.io
          publish_branch: main
          publish_dir: ./build
          allow_empty_commit: true
