name: Python script wencai

on:
  push:
    branches:
      - main

jobs:
  collect_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -U -r requirements.txt

    - name: Run Python script
      run: |
        python get-wencai.py

    - name: Commit and push changes
      uses: actions/github-script@v3
      with:
        script: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add stock_data.csv
          git add stock_data.md
          git commit -m "Update stock data" || echo "No changes to commit"
          git push origin main