name: Python script wencai

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install pywencai pandas tabulate

    - name: Get stock data
      run: |
       python wencai.py

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        message: "Update stock data {mtime}"
        branch: gh-pages
